MackEcom/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('product/<slug>/', views.ProductDetailView.as_view(), name='product'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('product/add-product/<slug>/', views.add_to_cart, name='add_product'),
    path('product/remove-product/<slug>', views.remove_from_cart, name='remove_from_cart'),
    path('summary/', views.SummaryView.as_view(), name='order-summary')
]

django-allauth-master/allauth/account/urls.py
from django.urls import path, re_path

from . import views


urlpatterns = [
    path("signup/", views.signup, name="account_signup"),
    path("login/", views.login, name="account_login"),
    path("logout/", views.logout, name="account_logout"),
    path("password/change/", views.password_change,
         name="account_change_password"),
    path("password/set/", views.password_set, name="account_set_password"),
    path("inactive/", views.account_inactive, name="account_inactive"),

    # E-mail
    path("email/", views.email, name="account_email"),
    path("confirm-email/", views.email_verification_sent,
         name="account_email_verification_sent"),
    re_path(r"^confirm-email/(?P<key>[-:\w]+)/$", views.confirm_email,
            name="account_confirm_email"),

    # password reset
    path("password/reset/", views.password_reset,
         name="account_reset_password"),
    path("password/reset/done/", views.password_reset_done,
         name="account_reset_password_done"),
    re_path(r"^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
            views.password_reset_from_key,
            name="account_reset_password_from_key"),
    path("password/reset/key/done/", views.password_reset_from_key_done,
         name="account_reset_password_from_key_done"),
]

django-allauth-master/allauth/socialaccount/providers/agave/urls.py
from allauth.socialaccount.providers.agave.provider import AgaveProvider
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns


urlpatterns = default_urlpatterns(AgaveProvider)

django-allauth-master/allauth/socialaccount/providers/asana/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import AsanaProvider


urlpatterns = default_urlpatterns(AsanaProvider)

django-allauth-master/allauth/socialaccount/providers/auth0/urls.py
# -*- coding: utf-8 -*-
from allauth.socialaccount.providers.auth0.provider import Auth0Provider
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns


urlpatterns = default_urlpatterns(Auth0Provider)

django-allauth-master/allauth/socialaccount/providers/azure/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import AzureProvider


urlpatterns = default_urlpatterns(AzureProvider)

django-allauth-master/allauth/socialaccount/providers/baidu/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import BaiduProvider


urlpatterns = default_urlpatterns(BaiduProvider)

django-allauth-master/allauth/socialaccount/providers/bitly/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import BitlyProvider


urlpatterns = default_urlpatterns(BitlyProvider)

django-allauth-master/allauth/socialaccount/providers/box/urls.py
from allauth.socialaccount.providers.oauth.urls import default_urlpatterns

from .provider import BoxOAuth2Provider


urlpatterns = default_urlpatterns(BoxOAuth2Provider)

django-allauth-master/allauth/socialaccount/providers/cern/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import CernProvider


urlpatterns = default_urlpatterns(CernProvider)

django-allauth-master/allauth/socialaccount/providers/daum/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import DaumProvider


urlpatterns = default_urlpatterns(DaumProvider)

django-allauth-master/allauth/socialaccount/providers/edx/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import EdxProvider


urlpatterns = default_urlpatterns(EdxProvider)

django-allauth-master/allauth/socialaccount/providers/exist/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import ExistProvider


urlpatterns = default_urlpatterns(ExistProvider)

django-allauth-master/allauth/socialaccount/providers/fxa/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import FirefoxAccountsProvider


urlpatterns = default_urlpatterns(FirefoxAccountsProvider)

django-allauth-master/allauth/socialaccount/providers/hubic/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import HubicProvider


urlpatterns = default_urlpatterns(HubicProvider)

django-allauth-master/allauth/socialaccount/providers/line/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import LineProvider


urlpatterns = default_urlpatterns(LineProvider)

django-allauth-master/allauth/socialaccount/providers/vk/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import VKProvider


urlpatterns = default_urlpatterns(VKProvider)

django-allauth-master/allauth/socialaccount/providers/xing/urls.py
from allauth.socialaccount.providers.oauth.urls import default_urlpatterns

from .provider import XingProvider


urlpatterns = default_urlpatterns(XingProvider)

django-allauth-master/allauth/socialaccount/providers/ynab/urls.py
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

from .provider import YNABProvider


urlpatterns = default_urlpatterns(YNABProvider)

django-allauth-master/allauth/socialaccount/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('login/cancelled/', views.login_cancelled,
         name='socialaccount_login_cancelled'),
    path('login/error/', views.login_error,
         name='socialaccount_login_error'),
    path('signup/', views.signup, name='socialaccount_signup'),
    path('connections/', views.connections, name='socialaccount_connections')
]

django-allauth-master/allauth/urls.py
from importlib import import_module

from django.urls import include, path

from allauth.socialaccount import providers

from . import app_settings


urlpatterns = [path('', include('allauth.account.urls'))]

if app_settings.SOCIALACCOUNT_ENABLED:
    urlpatterns += [path('social/', include('allauth.socialaccount.urls'))]

# Provider urlpatterns, as separate attribute (for reusability).
provider_urlpatterns = []
for provider in providers.registry.get_list():
    try:
        prov_mod = import_module(provider.get_package() + '.urls')
    except ImportError:
        continue
    prov_urlpatterns = getattr(prov_mod, 'urlpatterns', None)
    if prov_urlpatterns:
        provider_urlpatterns += prov_urlpatterns
urlpatterns += provider_urlpatterns

django-allauth-master/example/example/urls.py
from django.urls import include, path
from django.contrib import admin
from django.views.generic.base import TemplateView

admin.autodiscover()

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html')),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/',
         TemplateView.as_view(template_name='profile.html')),
    path('admin/', admin.site.urls),
]

templates/base.html
{% load static %}
{% load cart_template_tags %}

<head>
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}


  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Material Design Bootstrap</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="{% static 'MackEcom/css/bootstrap.min.css' %}">
  <!-- Material Design Bootstrap -->
  <link rel="stylesheet" href="{% static 'MackEcom/css/mdb.min.css' %}">
  <!-- Your custom styles (optional) -->
  <link rel="stylesheet" href="{% static 'MackEcom/css/style.min.css' %}">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

<body>
 <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar mb-5">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="{% url 'core:home' %}" target="_blank">
        <strong class="blue-text">MackEcom</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                {% if request.user.is_authenticated %}
                  <a class="nav-link waves-effect" href="{% url 'core:checkout' %}"
                  target="_blank">Checkout</a>
                {% endif %}
              </li>
            </ul>

        <!-- Right -->

          <div class="nav-item navbar-nav nav-flex-icons ">

              {% if request.user.is_authenticated %}

                  <a class="nav-link waves-effect clearfix d-none d-sm-inline-block" href="{% url 'account_logout' %}">
                     <small> Logout </small>
                  </a>

                  <a class="nav-link waves-effect" href="{% url 'core:order-summary'%}">
                        <i class="fas fa-shopping-cart"></i>
                       {% if request.user|cart_item_count %}
                           <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }}</span>
                        {% endif %}
                           <span class="clearfix d-none d-sm-inline-block"> Cart </span>
                  </a>

              {% else %}

                  <a class="nav-link waves-effect clearfix d-none d-sm-inline-block" href="{% url 'account_login' %}">
                    Login
                  </a>

                  <a class="nav-link waves-effect clearfix d-none d-sm-inline-block" href="{% url 'account_signup' %}">
                    Sign Up
                  </a>

              {% endif %}

          </div>


      </div>

    </div>
  </nav>
  <!-- Navbar -->



<div class="pb-5">
 {% block body %}

    {% if messages %}
    <div>
      <strong>Messages:</strong>
      <ul>
        {% for message in messages %}
        <li>{{message}}</li>
        {% endfor %}
      </ul>
    </div>
    {% endif %}

    {% endblock %}

 <!-- Django Allauth -->
    {% block content  %}


    {% endblock content %}

 {% block extra_body %}
    {% endblock %}
    {% if is_paginated %}
      <!--Pagination-->
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

            {% if page_obj.has_previous %}
              <!--Arrow left-->
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
                  <span class="sr-only">Previous</span>
                </a>
              </li>
            {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>
        <!--Arrow Right-->
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
            {% endif %}
        </ul>
      </nav>
      <!--Pagination-->
 {% endif %}
</div>
<!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/manas.kundu.9" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://github.com/Manas377" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2020 Copyright:
      <a href="#" target="_blank"> MackEcom.com </a>
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->
{#static_files/MackEcom/js/bootstrap.min.js#}
  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'MackEcom/js/jquery-3.4.1.min.js'%}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'MackEcom/js/popper.min.js'%}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'MackEcom/js/bootstrap.min.js'%}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'MackEcom/js/mdb.min.js'%}"></script>
  <script type="text/javascript" src="{% static 'MackEcom/js/conditional.js'%}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();


  </script>

</body>
</html>

templates/cart-summary.html
{% extends 'base.html' %}


{% block content %}


  <!--Main layout-->
<main>
  <div class="mt-5 container pt-5">
        {% if request.user.is_authenticated %}
         <h1>Order Summary</h1>
              <div class="table-responsive text-nowrap">

                  <table class="table">

                    <thead>
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">Product</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Price</th>
                        <th scope="col">Discounted Price</th>
                        <th scope="col">Total Price</th>
                      </tr>
                    </thead>

                    <tbody>
                    {% for item in object.items.all %}
                        <tr>
                            <th scope="row">{{ forloop.counter}}</th>
                            <td>{{ item.item.title }}</td>
                            <td>{{ item.qty }}</td>
                            <td>₹ {{ item.item.price }}</td>

                            {% if item.item.discounted_price %}
                                <td>₹ {{ item.item.discounted_price }}</td>
                            {% else %}
                                <td>N.A</td>
                            {% endif %}
                            <td>₹ {{ item.total_price }}</td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td colspan="4"> </td>
                        <td><strong>Order Total: </strong></td>
                        <td><strong>₹ {{ object.cart_total }}</strong></td>
                    </tr>
                    </tbody>
                  </table>
               </div>

            {% else %}

                <h1> Sign In to View Your Cart</h1>

        {% endif %}
  </div>
</main>
  <!--Main layout-->

{% endblock content %}

templates/checkout-page.html
{% extends 'base.html' %}
{% block content %}
  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container wow fadeIn">


      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout form</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Card-->
          <div class="card">


            <!--Card content-->
            <form class="card-body" method="post">
            {% csrf_token %}

                <!--Apartment-->
              <div class="md-form mb-5">
                  {{ form.apartment }}
              </div>

                <!--address-->
              <div class="md-form mb-5">
                  {{ form.address1 }}
              </div>

              <!--address-2-->
              <div class="md-form mb-5">
              {{ form.address2 }}
              </div>

              <!--Grid row-->
              <div class="row">

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">

                  <label for="state">State</label>

                  <select class="custom-select d-block w-100" id="state" name="state" required>
                    <option value="">Choose...</option>

                      {% for x,y in form.fields.state.choices %}
                          <option value="{{ x }}" {% if form.state.value == x%}selected{% endif %}>{{ y }}</option>
                      {% endfor %}
                  </select>

                </div>

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">

                  <label for="zip">Zip</label>
                  {{ form.zip }}
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>

                </div>

                <div class="col-lg-4 col-md-6 mb-4">

                  <label for="city">city</label>
                  {{ form.city }}
                  <div class="invalid-feedback">
                    city code required.
                  </div>

                </div>
              </div>
              <!--Grid row-->

              <hr>

              <div class="custom-control custom-checkbox">
                <input type="checkbox" value=1 class="custom-control-input" id="{{ form.same_billing_address.id_for_label }}"
                name="same-billing">
                <label class="custom-control-label" for="{{ form.same_billing_address.id_for_label }}">
                    Shipping address is the same as my billing address</label>
              </div>

              <div class="custom-control custom-checkbox">
                <input value=1 type="checkbox" class="custom-control-input" id="{{ form.save_info.id_for_label}}"
                name="save-info">
                <label class="custom-control-label" for="{{ form.save_info.id_for_label }}">Save this information for next time</label>
              </div>

              <hr>

              <div class="d-block my-3">
                {% for x,y in form.fields.payment_info.choices %}
                  <div class="custom-control custom-radio">
                  <input id="{{ x }}" name="payment_info" value="{{ x }}" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="{{ x }}">{{ y }}</label>
                </div>
                  {% endfor %}
              </div>

              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 mb-4">

          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">3</span>
          </h4>

          <!-- Cart -->
          <ul class="list-group mb-3 z-depth-1">

            {% for obj in cart.items.all %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">{{ obj.item.title }}</h6>
                <small class="text-muted">{{ obj.item.description|truncatechars:40}}</small>
              </div>
              {% if obj.item.discounted_price %}
              <span class="text-muted">{{ obj.item.discounted_price }}</span>
                  {% else %}
                  <span class="text-muted">{{ obj.item.price }}</span>
              {% endif %}
            </li>
              {% endfor %}



            <li class="list-group-item d-flex justify-content-between">
              <span>Total (INR)</span>
              <strong>₹ {{ cart.cart_total }}</strong>
            </li>
          </ul>
          <!-- Cart -->

{#          <!-- Promo code -->#}
{#          <form class="card p-2">#}
{#            <div class="input-group">#}
{#              <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2">#}
{#              <div class="input-group-append">#}
{#                <button class="btn btn-secondary btn-md waves-effect m-0" type="button">Redeem</button>#}
{#              </div>#}
{#            </div>#}
{#          </form>#}
{#          <!-- Promo code -->#}

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->
    </div>
  </main>
  <!--Main layout-->

{% endblock %}

templates/home-page.html
{% extends 'base.html' %}


{% block content %}


  <!--Main layout-->
  <main class="mt-5">
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-4 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">

          <!--Grid column-->
            {% for item in object_list %}
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                <img style="height: 250px; width:auto" src="{{ item.image.url }}" class="card-img-top"
                  alt="">
                <a>
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="{{ item.get_absolute_url }}" class="grey-text">
                  <h5>{{ item.get_category_display }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{% url 'core:product' slug=item.slug %}" class="dark-grey-text">{{ item.title }}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>{{ item.price }}</strong>
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
            {% endfor %}

        </div>


      </section>
      <!--Section: Products v.3-->



    </div>
  </main>
  <!--Main layout-->

{% endblock content %}

templates/item_list.html
{% extends 'base.html' %}

{% block content %}

    <h3>List Of Items</h3>
    {% for item in items %}
    <p>{{item}}</p>
    {% endfor %}

{% endblock %}

templates/product-page.html
{% extends 'base.html' %}


{% block content %}


  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="{{ object.image.url }}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
              </a>
            </div>

            <p class="lead">
              {% if object.discounted_price %}
                  <span class="mr-1"><del>{{ object.price }}</del></span>
                    <span>{{ object.discounted_price }}</span>
               {% else %}
                     <span>{{ object.price }}</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">{{object.title}}</p>

            <p>{{ object.description }}</p>

{#            <form class="d-flex justify-content-left">#}
{#              <!-- Default input -->#}
{#              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">#}
{#              <button class="btn btn-primary btn-md my-0 p" type="submit" targ><a#}
{#                      href="{% url object.get_add_to_cart_url %}">Add to cart</a>#}
{#                <i class="fas fa-shopping-cart ml-1"></i>#}
{#              </button>#}
{##}
{#            </form>#}
                          {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}><small>{{ message }}</small></li>
                    {% endfor %}
                </ul>
                {% endif %}
                <a class="btn btn-primary btn-md my-0 p"
                    href="{{ object.get_add_to_cart_url }}">Add to cart
                 <i class="fas fa-shopping-cart ml-1"></i>
                </a>

                <a class="btn btn-danger btn-md my-0 p"
                    href="{% url 'core:remove_from_cart' slug=object.slug%}">Remove
              </a>


          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

 {% endblock %}